config/routes.rb
Rails.application.routes.draw do
  #get 'blogs/index'
  #get 'blogs/show'

  # resources :blogs
  # resources :projects
  resources :projects, :blogs

  resources :courses

  # Defines the root path route ("/")
  root "welcome#index"
  get "welcome/index"
  #resources :welcomes

  #get "welcome/about"
  #get "/about/" => 'welcome#about'
  #root "welcome#index"

  resources :students

  # resources :students do
  #   member do
  #     get :personal_details
  #   end
  #   collection do
  #     get :active
  #   end
  # end

  #get :personal_details, on: :member  #this is only one member action of resource

  # member routes require id of a resource to perform an action like for (show, edit, update, destroy)
  # so it is the show, edit, update, destroy it is member action because it need id to perform action
  # collection routes does not require id of resource like (index, create, new)

  get "students/test"   #custom routes

  namespace :admin do
    resources :students
  end


end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :student
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.includes(:student)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blogs_path, notice: 'Blog has been created successfully'
    else
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    debugger
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_path(@blog), notice: 'Blog has been updated successfully'
    else
      render :edit 
    end
  end


  private

  def blog_params
    params.require(:blog).permit(:title, :content, :student_id)
  end


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<p><%= notice %></p>
<%= form_with model: @blog do |form| %>

	<div>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</div>

	<div>
		<%= form.label :content %><br>
		<%= form.text_field :content %>
	</div>

	<div>
		<%= form.label :student_id %><br>
		<%= form.text_field :student_id %>
	</div>

	<div>
		<%= form.submit %>
	</div>

<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>
<%= render "form", blog: @blog %>

app/views/blogs/index.html.erb
<p><%= notice %></p>
<h1>blog details</h1>
<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Content</th>
			<th colspan="3">Actions</th>
		</tr>
	</thead>
	<tbody>
		<% @blogs.each do |blog| %>
			<tr>
				<td><%= blog.title %></td>
				<td><%= blog.content %></td>
				<td><%= link_to 'View', blog %></td>
				<td><%= link_to 'Edit', edit_blog_path(blog) %></td>
				<td><%= link_to 'Delete', blog, data: { "turbo-method": :delete } %></td>
			</tr>
		<% end %>
	</tbody>
</table>  

app/views/blogs/new.html.erb
<h1>New Blog</h1>
<%= render "form", blog: @blog %>

app/views/blogs/show.html.erb
<h1>Blogs#show</h1>
<p><%= notice %></p>
<p><strong>Title: </strong><%= @blog.title %></p>
<p><strong>Description: </strong><%= @blog.content %></p>