config/routes.rb
Rails.application.routes.draw do
  #get 'blogs/index'
  #get 'blogs/show'

  # resources :blogs
  # resources :projects
  resources :projects, :blogs

  resources :courses

  # Defines the root path route ("/")
  root "welcome#index"
  get "welcome/index"
  #resources :welcomes

  #get "welcome/about"
  #get "/about/" => 'welcome#about'
  #root "welcome#index"

  resources :students

  # resources :students do
  #   member do
  #     get :personal_details
  #   end
  #   collection do
  #     get :active
  #   end
  # end

  #get :personal_details, on: :member  #this is only one member action of resource

  # member routes require id of a resource to perform an action like for (show, edit, update, destroy)
  # so it is the show, edit, update, destroy it is member action because it need id to perform action
  # collection routes does not require id of resource like (index, create, new)

  get "students/test"   #custom routes

  namespace :admin do
    resources :students
  end


end

app/models/student.rb
class Student < ApplicationRecord
	has_one_attached :profile_image
	# validates :profile_image, presence: true, file_content_type: [:gif, :png, :jpg, :jpeg],
    #         size: { less_than: 2.megabytes , message: 'must be less than 2MB in size' }

    #validates :profile_image, presence: true, file_content_type: { allow: ['image/png', 'image/jpeg', 'image/gif'] }, size: { less_than: 2.megabytes, message: 'must be less than 2MB in size' }
    #validates :image_profile, presence: true, file_type: { in: ['image/jpeg', 'image/png'], message: 'must be a JPEG or PNG image' }
    validates :profile_image, file_content_type: { allow: ['image/jpeg', 'image/png'], message: 'must be a JPEG or PNG image' }

	has_many :blogs
	
	validates :first_name, :last_name, :email, presence: true
	validates :email, uniqueness: true
	validates :first_name, :last_name, length: { minimum: 2, maximum: 50 }
	validates :first_name, :last_name, format: { with: /\A[a-zA-Z]+\z/, message: 'only letters are allowed' }

	validate :validate_student_age  #custom validation

	has_and_belongs_to_many :courses
	has_many :student_projects
	has_many :projects, through: :student_projects
	before_create :display_greetings

	after_commit :display_student_age

	def display_greetings
		puts "hello, you executed before action callback"
	end

	def display_student_age
		if self.date_of_birth.present?
			age = Date.today.year - self.date_of_birth.year
			puts "======Age of student is #{age}====="
		else
			puts "=======Age cann't calculated without date_of_birth======"
		end
	end

	def validate_student_age
		if self.date_of_birth.present?
			age = Date.today.year - self.date_of_birth.year
			if age < 10
				errors.add(:age, 'please provide valid date_of_birth here. Age must be greater than 15')
			end
		end
	end
end

app/controllers/Admin/students_controller.rb
class Admin::StudentsController <ApplicationController
	#Implement CRUD operation
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	layout 'admin'
	include ApplicationHelper
	before_action :set_student, only: %i[show edit update destroy]
	helper_method :formatted_date

	def index
		@students = Student.all
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save
			redirect_to students_path, notice: 'Student has been created successfully'
		else
			render :new
		end
	end

	def show 	
		#@student = Student.find(params[:id])
	end

	def edit
		#@student = Student.find(params[:id])
		date = formatted_date(@student.date_of_birth)
	end

	def update
		#@student = Student.find(params[:id])
		if @student.update(student_params)
			redirect_to student_path(@student), notice: 'Student has been updated successfully'
		else
			render :edit 
		end
	end

	def destroy
		#@student = Student.find(params[:id]) 
		@student.destroy
		redirect_to students_path, notice: 'Student has been deleted successfully'
	end

	def test
	end
	# def create
	# 	@student = Student.new(
	# 	first_name: params[:student][:first_name],
	# 	last_name: params[:student][:last_name],
	# 	email: params[:student][:email]
	# 	)
	# 	if @student.save
	# 		redirect_to students_path
	# 	else
	# 		render :new
	# 	end
	# end

	private

	def student_params
		params.require(:student).permit(:first_name, :last_name, :email, :date_of_birth, :alternate_contact_number, :permanent_contact_number, :local_address, :permanent_address, :profile_image)
	end

	def set_student
		@student = Student.find(params[:id]) 
	end

	def formatted_date(date)
		date.strftime('%A, %b %d, %Y') if date.present?
	end
end

app/views/students/_form.html.erb
<p><%= notice %></p>
<%= form_with model: @student do |form| %>
	
	<% if @student.errors.any? %>
		<% @student.errors.full_messages.each do |message| %>
			<p> <%= message %></p>
		<% end %>
	<% end %>

	<div class="form-group">
		<%= form.label :first_name %>
		<%= form.text_field :first_name, class: "form-control form-control-lg" %>
	</div>
	<div class="form-group">
		<%= form.label :last_name %>
		<%= form.text_field :last_name, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :email %>
		<%= form.email_field :email, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :alternate_contact_number %>
		<%= form.text_field :alternate_contact_number, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :permanent_contact_number %>
		<%= form.text_field :permanent_contact_number, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :date_of_birth %>
		<%= form.date_field :date_of_birth, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :local_address %>
		<%= form.text_field :local_address, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :permanent_address %>
		<%= form.text_field :permanent_address, class: "form-control form-control-lg" %>
	</div>
	<div>
		<%= form.label :profile_image %><br>
		<%= form.file_field :profile_image %>
	</div>

	<div>
		<%= form.submit class: "btn btn-primary btn-lg" %>
	</div>
	
<% end %>

app/views/students/edit.html.erb
<div class="col-lg-8">
	<h1>Edit Student</h1>
	<%= render "form", student: @student %>
</div>

<%#= render partial: "form", locals: { student: @student } %>

app/views/students/index.html.erb
<div class="col-lg-8">
	<p><%= notice %></p>
	<h1>Students List</h1>
	<%= link_to 'New Student', new_student_path, class: "btn btn-primary btn-lg" %>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>First_Name</th>
				<th>Last_Name</th>
				<th>Email</th>
				<th colspan="3">Actions</th>
			</tr>
		</thead>
		<tbody>
			<% @students.each do |student| %>
				<tr>
					<td><%= student.first_name %></td>
					<td><%= student.last_name %></td>
					<td><%= student.email %></td>
					<td><%= link_to 'View', student %></td>
					<td><%= link_to 'Edit', edit_student_path(student) %></td>
					<td><%= link_to 'Delete', student, data: { "turbo-method": :delete } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>  
</div>

app/views/students/new.html.erb
<div class="col-lg-8">
	<h1>New Student</h1>
	<%= render "form", student: @student %>
</div>
<%#= render partial: "form", locals: { student: @student } %>

app/views/students/show.html.erb
<div class="col-lg-10">
	<div class="card rounded-0 shadow mt-5 mb-5">
		<div class="card-body">
			<p><%= notice %></p>
			<h1>student details</h1>
			<% if @student.profile_image.attached? %>
				<%= image_tag @student.profile_image, size: "250" %>
			<% end %>
			<p><strong>First Name: </strong><%= @student.first_name %></p>
			<p><strong>Last Name: </strong><%= @student.last_name %></p>
			<p><strong>Email: </strong><%= @student.email %></p>

			<% if @student.date_of_birth.present? %>
				<p><strong>Date_of_birth: </strong><%= formatted_date(@student.date_of_birth) %></p>
			<% end %>

			<p><strong>Alternate Contact Number: </strong><%= @student.alternate_contact_number %></p>
			<p><strong>Permanent Contact Number: </strong><%= @student.permanent_contact_number %></p>

			<p><strong>Local Address: </strong><%= @student.local_address %></p>
			<p><strong>Permanent Address: </strong><%= @student.permanent_address %></p>
			<%= link_to 'Back', students_path, class: "btn btn-primary" %>
			<%= link_to 'Edit', edit_student_path(@student), class: "btn btn-primary" %>
		</div>
	</div>
	
</div>